name: Generate 3D Contributions

on:
  # Run automatically every day at midnight
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contributions
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jaynikam2005
        with:
          USERNAME: jaynikam2005
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated 3D contributions" || exit 0
          git push